### ISSUE TITLE
Installation via zplug silently fails

### ISSUE THREAD

**Issue by henrebotha** [BuonOmo/yarn-completion#10]
- Zsh version: `zsh 5.8.1 (x86_64-ubuntu-linux-gnu)`
- zplug version: 2.4.2

I install using zplug, which works just fine, then restart my shell, but no completions get added. When I install this manually by just cloning & sourcing, it works correctly.

**Comment by henrebotha** [comment]
Hmm, actually, manual install only works if I enter `source ~/.yarn-completion…` in the command line directly. If I add it to my `.zshrc`, it also doesn't work.

**Comment by BuonOmo** [comment]
I think this could be fixed by moving the compdef to the top, using the comment version, that mixes better with zsh autoloading.

Could you try to apply the patch below and tell me if it works better with zplug?

```diff
diff --git a/yarn-completion.plugin.zsh b/yarn-completion.plugin.zsh
index a9e8229..61461e9 100644
--- a/yarn-completion.plugin.zsh
+++ b/yarn-completion.plugin.zsh
@@ -1,3 +1,4 @@
+#compdef yarn
 _yc_yarn_command() {
   echo "${words[2]}"
 }
@@ -99,4 +100,4 @@ _yc_zsh_better_yarn_completion() {
   esac
 }
 
-compdef _yc_zsh_better_yarn_completion yarn
+_yc_zsh_better_yarn_completion "$@"
```

**Comment by henrebotha** [comment]
I forked this repo and applied your suggested patch, then installed the fork using zplug. It breaks; here's the result of me typing `yarn ` and then pressing <kbd>Tab</kbd>.

```
2022-11-07 15:59:54 hbotha ~dev
» yarn _yc_zsh_better_yarn_completion:19: command not found: _yarn
_yc_zsh_better_yarn_completion:2: command not found: _yarn
_yc_zsh_better_yarn_completion:19: command not found: _yarn
_yc_zsh_better_yarn_completion:2: command not found: _yarn
2022-11-07 15:59:54 hbotha ~dev
» yarn 
```

**Comment by BuonOmo** [comment]
This is OK. You can try again now and it should work.

Also, try and install the default `_yarn` completion as well for a richer experience. For instance using `zsh-completions`

**Comment by henrebotha** [comment]
Fixed.
