### ISSUE TITLE
Autocomplete run script even without the `run` keyword

### ISSUE THREAD

**Issue by borekb** [BuonOmo/yarn-completion#2]
It would be awesome if a script name could be suggested even if the `run` keyword is not used.

For example, I typically run `yarn tests`, not `yarn run tests`. We also have a lot of "nested" scripts like `yarn build:frontend` and `yarn build:backend`. Here, again, it would be great if I could type `yarn build:`, press `Tab` and the two build scripts would be suggested.

Note that I understand that it's a bit tricky to guess when one wants to run a script vs. some Yarn subcommand. But hopefully, it could be done somehow.

**Comment by BuonOmo** [comment]
This seems quite tricky indeed. I've only forked this and replace names ^^.

However, a part of this idea has been implemented [here](https://github.com/BuonOmo/yarn-completion/pull/1), and I'd be glad to dig more into it when I have some time available (this won't be soon though...).

If you have any idea or any time to dedicate to this issue, I'd be glad to merge it.

**Comment by borekb** [comment]
Thanks, I missed that PR. Zsh code is out of my capabilities, unfortunately :) So I'll patiently wait if someone implements it.

**Comment by BuonOmo** [comment]
This is actually really non-trivial, and would conflict with the idea of defaulting to the default yarn completion. Hence I'm closing it now
