### ISSUE TITLE
yarn version tab not work

### ISSUE THREAD

**Issue by Diluka** [BuonOmo/yarn-completion#7]
should work like built-in `yarn` plugin

**Comment by BuonOmo** [comment]
Hey @Diluka, thanks for reporting!

Could you either add more reproduction information, or a PR?

**Comment by Diluka** [comment]
this is the built-in plugin
![image](https://user-images.githubusercontent.com/3766084/138386757-04a37345-8dd0-4ea1-a973-f84805d72227.png)

this plugin just show nothing
![image](https://user-images.githubusercontent.com/3766084/138386864-edb1d1cf-c3f6-4aca-b276-fc55e9783ff4.png)

**Comment by BuonOmo** [comment]
@Diluka Ok thanks, and is there any reason to prefer this plugin over the default `yarn` completion ? Otherwise I could just update the readme and deprecate the repository

**Comment by BuonOmo** [comment]
@Diluka actually, I think I finally found a way to fix it, wdyt?
